/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import Helper.helperAgencia;
import Helper.helperContas;
import agencias.Agencia;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class AgenciaView extends javax.swing.JDialog {

    /**
     * Creates new form AgenciaView
     */
    public AgenciaView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jTcodigo1 = new javax.swing.JTextField();
        btincluir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTdescricao = new javax.swing.JTextField();
        jbexcluir = new javax.swing.JButton();
        jbalterar = new javax.swing.JButton();
        jtimprimir = new javax.swing.JButton();
        jtimprimir1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel8.setText("Código:");

        jTcodigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcodigo1ActionPerformed(evt);
            }
        });

        btincluir.setText("Incluir");
        btincluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btincluirActionPerformed(evt);
            }
        });

        jLabel9.setText("Descrição: ");

        jTdescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTdescricaoActionPerformed(evt);
            }
        });

        jbexcluir.setText("Excluir");
        jbexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbexcluirActionPerformed(evt);
            }
        });

        jbalterar.setText("Alterar");
        jbalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbalterarActionPerformed(evt);
            }
        });

        jtimprimir.setText("Imprimir contas corrente");
        jtimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtimprimirActionPerformed(evt);
            }
        });

        jtimprimir1.setText("Imprimir contas poupança");
        jtimprimir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtimprimir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbalterar)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbexcluir)
                                .addGap(85, 85, 85)
                                .addComponent(btincluir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTcodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtimprimir1)
                            .addComponent(jtimprimir))))
                .addGap(0, 55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTcodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbexcluir)
                    .addComponent(btincluir)
                    .addComponent(jbalterar))
                .addGap(18, 18, 18)
                .addComponent(jtimprimir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtimprimir1)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTcodigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcodigo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcodigo1ActionPerformed

    private void btincluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btincluirActionPerformed
        Agencia temp = null;
        
        int codigo = 0;
        String descricao = null;
        try {
            codigo = Integer.parseInt(jTcodigo1.getText().trim());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido.");
            return;
        }

        descricao = jTdescricao.getText();
        if (descricao.trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Campo descrição inválido.");
            return;
        }
        temp = new Agencia(codigo, descricao);
        helperAgencia.getInstance().addAgencia(temp);
        JOptionPane.showMessageDialog(this, "Objeto incluído!");
    }//GEN-LAST:event_btincluirActionPerformed

    private void jTdescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTdescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTdescricaoActionPerformed

    private void jbexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbexcluirActionPerformed
        // TODO add your handling code here:
        
        int codigo = 0;
        try {
            codigo = Integer.parseInt(jTcodigo1.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Digite um valor para excluir.");
            return;
        }
        helperAgencia agenciaHelper = helperAgencia.getInstance();
        int totalObjetos = 0;
        totalObjetos = agenciaHelper.excluir(codigo);
        if (totalObjetos > 0) {
            JOptionPane.showMessageDialog(this, "Total de objetos excluidos: " + totalObjetos);
        } else {
            JOptionPane.showMessageDialog(this, "Código não encontrado.");
        }
    }//GEN-LAST:event_jbexcluirActionPerformed

    private void jbalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbalterarActionPerformed
        // TODO add your handling code here:
        
        int codigo = 0;
        String descricao;
        try {
            codigo = Integer.parseInt(jTcodigo1.getText());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Digite um valor para alterar.");
            return;
        }

        descricao = jTdescricao.getText();
        if (descricao.trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Campo descrição inválido.");
            return;
        }

        Agencia agencia = new Agencia(codigo, descricao);
        if (helperAgencia.getInstance().alterar(agencia) >= 0) {
            JOptionPane.showMessageDialog(this, "Objeto alterado.");
        } else {
            JOptionPane.showMessageDialog(this, "Objeto não slterado.");
        }

        
    }//GEN-LAST:event_jbalterarActionPerformed

    private void jtimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtimprimirActionPerformed
        helperAgencia.getInstance().imprimirAgencias();
        int agencia = 0;
        agencia = Integer.parseInt(jTcodigo1.getText());
        try{
            agencia = Integer.parseInt(jTcodigo1.getText().trim());
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Digite um código: ");
            return;
        }
        helperContas.getInstance().listarContasCorrent(agencia);

        
    }//GEN-LAST:event_jtimprimirActionPerformed

    private void jtimprimir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtimprimir1ActionPerformed
        helperAgencia.getInstance().imprimirAgencias();
        int agencia = 0;
        agencia = Integer.parseInt(jTcodigo1.getText());
        try{
            agencia = Integer.parseInt(jTcodigo1.getText().trim());
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Digite um código: ");
            return;
        }
        helperContas.getInstance().listarContasPoup(agencia);

    }//GEN-LAST:event_jtimprimir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgenciaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgenciaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgenciaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgenciaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgenciaView dialog = new AgenciaView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btincluir;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTcodigo1;
    private javax.swing.JTextField jTdescricao;
    private javax.swing.JButton jbalterar;
    private javax.swing.JButton jbexcluir;
    private javax.swing.JButton jtimprimir;
    private javax.swing.JButton jtimprimir1;
    // End of variables declaration//GEN-END:variables
}
