package view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author pedro
 */
import Helper.helperContas;
import Helper.helperAgencia;
import conta.contaCorrente;
import javax.swing.JOptionPane;
import agencias.Agencia;
public class contacorrenteView extends javax.swing.JDialog {



    /**
     * Creates new form contacorrente
     */
    public contacorrenteView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtendereco = new javax.swing.JTextField();
        jtrg = new javax.swing.JTextField();
        jtcpf = new javax.swing.JTextField();
        jtrenda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btincluir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtnome = new javax.swing.JTextField();
        jtagencia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTcodigo = new javax.swing.JTextField();
        jbexcluir = new javax.swing.JButton();
        jbalterar = new javax.swing.JButton();
        jtpesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcpfActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Endereço:");

        jLabel3.setText("CPF:");

        jLabel4.setText("RG:");

        btincluir.setText("Incluir");
        btincluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btincluirActionPerformed(evt);
            }
        });

        jLabel5.setText("Renda:");

        jLabel6.setText("Agencia:");

        jLabel7.setText("Código:");

        jbexcluir.setText("Excluir");
        jbexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbexcluirActionPerformed(evt);
            }
        });

        jbalterar.setText("Alterar");
        jbalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbalterarActionPerformed(evt);
            }
        });

        jtpesquisar.setText("Pesquisar");
        jtpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtpesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtrenda, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btincluir)
                                    .addComponent(jbexcluir))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtrg, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtagencia, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jtpesquisar)))
                        .addGap(204, 204, 204)))
                .addComponent(jbalterar)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1)
                    .addComponent(jtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtrenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtagencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtpesquisar)
                    .addComponent(btincluir)
                    .addComponent(jbalterar))
                .addGap(30, 30, 30)
                .addComponent(jbexcluir)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btincluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btincluirActionPerformed
        contaCorrente temp = null;
        String nome = null, enderec = null;
        long cpf = 0, rg = 0;
        double renda = 0;
        int agen = 0;
        int codigo = 0;
        
        nome = jtnome.getText();
        if (nome.trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Campo nome inválido.");
            return;
        }
        enderec = jtendereco.getText();
        if (enderec.trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Campo endereço inválido.");
            return;
        }
        
        try{
            cpf = Integer.parseInt(jtcpf.getText().trim());
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Digite o cpf: ");
            return;
        }
        try{
            rg = Integer.parseInt(jtrg.getText().trim());
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Digite o RG: ");
            return;
        }
        try{
            renda = Double.parseDouble(jtrenda.getText().trim());
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Digite a renda: ");
            return;
        }
        
        try{
            agen = Integer.parseInt(jtagencia.getText().trim());
            if(agen == helperAgencia.getInstance().pesquisar(Integer.parseInt(jtagencia.getText().trim()))){
                jtagencia.setText(""+ agen);
                codigo = helperContas.getInstance().soma();
                temp = new contaCorrente(nome, enderec, cpf, rg, renda, agen, codigo);
                helperContas.getInstance().addContaCorrente(temp);
        
                jTcodigo.setText(Integer.toString(codigo));
                JOptionPane.showMessageDialog(this, "Objeto incluído!");
           }else{
                JOptionPane.showMessageDialog(this, "Agencia inexistente.");
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Digite uma agencia valida: ");
            return;
        }        

    }//GEN-LAST:event_btincluirActionPerformed

    private void jbexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbexcluirActionPerformed
        // TODO add your handling code here:
        int codigo;
        try{
            codigo = Integer.parseInt(jTcodigo.getText().trim());
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Digite um código: ");
            return;
        }
        
        helperContas helpercorrente = helperContas.getInstance();
        int totalObjetos = 0;
        totalObjetos = helpercorrente.excluirCorrente(codigo);
        if (totalObjetos > 0) {
            JOptionPane.showMessageDialog(this, "Total de objetos excluidos: " + totalObjetos);
        } else {
            JOptionPane.showMessageDialog(this, "Código não encontrado.");
        }
        
    }//GEN-LAST:event_jbexcluirActionPerformed

    private void jbalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbalterarActionPerformed
        // TODO add your handling code here:
        contaCorrente temp = null;
        String nome = null, enderec = null;
        long cpf = 0, rg = 0;
        double renda = 0;
        int agen = 0;
        int codigo = 0;
        
        nome = jtnome.getText();
        if (nome.trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Campo nome inválido.");
            return;
        }
        enderec = jtendereco.getText();
        if (enderec.trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Campo endereço inválido.");
            return;
        }
        try{
            cpf = Integer.parseInt(jtcpf.getText().trim());
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Digite o cpf: ");
            return;
        }
        try{
            rg = Integer.parseInt(jtrg.getText().trim());
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Digite o RG: ");
            return;
        }
        try{
            renda = Double.parseDouble(jtrenda.getText().trim());
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Digite a renda: ");
            return;
        }
        try{
            agen = Integer.parseInt(jtagencia.getText().trim());
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Digite a agencia: ");
            return;
        }
        try{
            codigo = Integer.parseInt(jTcodigo.getText().trim());
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Digite um código: ");
            return;
        }
        contaCorrente contacorrente = new contaCorrente(nome, enderec, cpf, rg, renda, agen, codigo);
        if (helperContas.getInstance().alterarCorrente(contacorrente) >= 0) {
            JOptionPane.showMessageDialog(this, "Objeto alterado.");
        } else {
            JOptionPane.showMessageDialog(this, "Objeto não alterado.");
        }
    }//GEN-LAST:event_jbalterarActionPerformed

    private void jtpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtpesquisarActionPerformed
        // TODO add your handling code here:
        
        helperContas helpercontas = helperContas.getInstance();
        contaCorrente temp = null;
        int codigo = 0;
        codigo = Integer.parseInt(jTcodigo.getText());
        try{
            codigo = Integer.parseInt(jTcodigo.getText().trim());
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Digite um código: ");
            return;
        }

        temp = helpercontas.pesquisarCorrente(codigo);
        if (temp != null) {
            JOptionPane.showMessageDialog(this, "Objeto encontrado." + temp);
            jTcodigo.setText(""+ temp.getCodigo());
            jtnome.setText("" + temp.getNome());
            jtendereco.setText("" + temp.getEndereco());
            jtcpf.setText("" + temp.getCpf());
            jtrg.setText("" + temp.getRg());
            jtrenda.setText("" + temp.getRenda());
            jtagencia.setText("" + temp.getAgencia());
        } else {
            JOptionPane.showMessageDialog(this, "Código não encontrado.");
        }

        
    }//GEN-LAST:event_jtpesquisarActionPerformed

    private void jtcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtcpfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(contacorrenteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(contacorrenteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(contacorrenteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(contacorrenteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                contacorrenteView dialog = new contacorrenteView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btincluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTcodigo;
    private javax.swing.JButton jbalterar;
    private javax.swing.JButton jbexcluir;
    private javax.swing.JTextField jtagencia;
    private javax.swing.JTextField jtcpf;
    private javax.swing.JTextField jtendereco;
    private javax.swing.JTextField jtnome;
    private javax.swing.JButton jtpesquisar;
    private javax.swing.JTextField jtrenda;
    private javax.swing.JTextField jtrg;
    // End of variables declaration//GEN-END:variables
}
